spring:
  application:
    name: userService
  datasource:
    url: jdbc:postgresql://localhost:5432/mana_service_users?createDatabaseIfNotExist=true&autoReconnect=true&useSSL=false
    username: postgres
    password: Rommel@19
    driver-class-name: org.postgresql.Driver
  mail:
    host: smtp.gmail.com
    port: 587
    username: tkayenie@gmail.com
    password: djesqkjaighgvedu
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            trust: smtp.gmail.com
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: user-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: zw.co.manaService.userService.event
    admin:
      fail-fast: false

  config:
    import: "optional:configserver:"

server:
  port: 8082

jwt:
  secret: 5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437
  expiration: 86400000 # 1 day

logging:
  level:
    zw.co.manaService: DEBUG
    org.springframework.security: DEBUG
app:
  frontend:
    url: http://localhost:3000